name: auth_ui_web_example
description: auth ui web example.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

publish_to: none

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
dependencies:
  firebase: ^9.0.2
  auth_ui_web:
    path: ../../auth_ui_web/
